spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: 1344
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  jmx:
    enabled: true
    default-domain: ums
    server:
      port: 1099
